// PDF rendering and HTML escaping shared by the letter emails.
//
// Moved verbatim out of src/app/api/webhooks/stripe/route.ts on 2026-09-11 so
// the Escalation Reply Letter fulfilment (src/lib/stage-reply-fulfilment.ts)
// renders the exact same PDF as the Standard and Premium letters. Route files
// may only export route handlers, which is why this lives in lib. The webhook
// still imports pdfkit through here, and next.config.ts already ships the
// .afm font files for that route.

import PDFDocument from "pdfkit";

export function generatePDF(content: string, title: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 65, right: 65 },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.moveTo(65, 45).lineTo(530, 45).strokeColor("#0d9488").lineWidth(2).stroke();
    doc.fontSize(9).fillColor("#64748b").text(title, 65, 52, { align: "right" });
    doc.moveDown(1);

    const lines = content.split("\n");
    let y = doc.y;
    for (const line of lines) {
      if (y > 750) {
        doc.addPage();
        y = 60;
        doc.y = y;
      }
      const trimmed = line.trim();
      if (trimmed.startsWith("RE:") || trimmed.startsWith("Dear ") || trimmed.startsWith("Yours ")) {
        doc.fontSize(11).fillColor("#1e293b").font("Helvetica-Bold");
        doc.text(trimmed, { lineGap: 4 });
        doc.font("Helvetica");
      } else if (trimmed === "") {
        doc.moveDown(0.4);
      } else if (trimmed.match(/^\d+\.\s/) || trimmed.startsWith("- ")) {
        doc.fontSize(10.5).fillColor("#334155").font("Helvetica");
        doc.text(trimmed, { lineGap: 3, indent: 15 });
      } else {
        doc.fontSize(10.5).fillColor("#334155").font("Helvetica");
        doc.text(trimmed, { lineGap: 3 });
      }
      y = doc.y;
    }

    doc.moveDown(2);
    doc.moveTo(65, doc.y).lineTo(530, doc.y).strokeColor("#e2e8f0").lineWidth(0.5).stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor("#94a3b8").text(
      "Generated by AppealAFine (appealafine.co.uk). Document preparation service, not legal advice.",
      { align: "center" }
    );
    doc.end();
  });
}

export function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
