import { NextResponse } from "next/server";
import { Resend } from "resend";

function getResend() {
  if (!process.env.RESEND_API_KEY) {
    throw new Error("RESEND_API_KEY is not set");
  }
  return new Resend(process.env.RESEND_API_KEY);
}

interface SendLetterRequest {
  email: string;
  letterContent: string;
  fineType: string;
  operatorName?: string;
  councilName?: string;
  vehicleReg?: string;
  productName: string;
  escalationLetter?: string;
  evidenceChecklist?: string;
}

export async function POST(request: Request) {
  try {
    const body: SendLetterRequest = await request.json();

    if (!body.email || !body.email.includes("@")) {
      return NextResponse.json({ error: "Valid email is required" }, { status: 400 });
    }

    if (!body.letterContent) {
      return NextResponse.json({ error: "Letter content is required" }, { status: 400 });
    }

    const recipient = body.operatorName || body.councilName || "the parking operator";
    const subject = `Your Appeal Letter is Ready - ${recipient}`;

    let htmlBody = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
        <div style="background: #0d9488; padding: 24px; text-align: center; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 20px;">Your Appeal Letter is Ready</h1>
        </div>

        <div style="padding: 24px; background: #f8fafc; border: 1px solid #e2e8f0;">
          <p style="margin-top: 0;">Hi,</p>
          <p>Your personalised appeal letter for the ${body.fineType === "private" ? "parking charge" : "PCN"} from <strong>${recipient}</strong> is below.</p>

          ${body.vehicleReg ? `<p style="font-size: 14px; color: #64748b;">Vehicle: ${body.vehicleReg}</p>` : ""}

          <div style="background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 20px 0;">
            <h3 style="margin-top: 0; font-size: 14px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em;">Appeal Letter</h3>
            <pre style="white-space: pre-wrap; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; line-height: 1.6; color: #334155; margin: 0;">${escapeHtml(body.letterContent)}</pre>
          </div>`;

    if (body.escalationLetter) {
      htmlBody += `
          <div style="background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 20px 0;">
            <h3 style="margin-top: 0; font-size: 14px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em;">Escalation Letter (if your appeal is rejected)</h3>
            <pre style="white-space: pre-wrap; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; line-height: 1.6; color: #334155; margin: 0;">${escapeHtml(body.escalationLetter)}</pre>
          </div>`;
    }

    if (body.evidenceChecklist) {
      htmlBody += `
          <div style="background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 20px; margin: 20px 0;">
            <h3 style="margin-top: 0; font-size: 14px; color: #92400e; text-transform: uppercase; letter-spacing: 0.05em;">Evidence Checklist</h3>
            <pre style="white-space: pre-wrap; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; line-height: 1.6; color: #78350f; margin: 0;">${escapeHtml(body.evidenceChecklist)}</pre>
          </div>`;
    }

    htmlBody += `
          <div style="background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 8px; padding: 16px; margin: 20px 0;">
            <h4 style="margin-top: 0; color: #0f766e; font-size: 14px;">Before you send</h4>
            <ul style="font-size: 13px; color: #115e59; padding-left: 20px; margin-bottom: 0;">
              <li>Replace [YOUR NAME] and [YOUR ADDRESS] with your real details</li>
              <li>Review the letter and adjust any details as needed</li>
              <li>Attach any supporting evidence (photos, receipts, screenshots)</li>
              <li>Keep a copy of everything you send</li>
              <li>Send within your appeal deadline</li>
            </ul>
          </div>

          <p style="font-size: 13px; color: #94a3b8; margin-bottom: 0;">
            This letter was generated by FineCheck (appealafine.co.uk).
            We provide document preparation services and are not a law firm.
            If you need legal advice, please consult a qualified solicitor.
          </p>
        </div>

        <div style="background: #1e293b; padding: 16px; text-align: center; border-radius: 0 0 12px 12px;">
          <p style="color: #94a3b8; font-size: 12px; margin: 0;">
            FineCheck | <a href="https://appealafine.co.uk" style="color: #5eead4;">appealafine.co.uk</a>
          </p>
        </div>
      </div>`;

    const resend = getResend();
    const { error } = await resend.emails.send({
      from: "Appeal a Fine <appeals@appealafine.co.uk>",
      to: body.email,
      subject,
      html: htmlBody,
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Send letter error:", error);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
