import { NextResponse } from "next/server";
import { Resend } from "resend";
import PDFDocument from "pdfkit";

function getResend() {
  if (!process.env.RESEND_API_KEY) {
    throw new Error("RESEND_API_KEY is not set");
  }
  return new Resend(process.env.RESEND_API_KEY);
}

interface SendLetterRequest {
  email: string;
  letterContent: string;
  fineType: string;
  operatorName?: string;
  councilName?: string;
  vehicleReg?: string;
  location?: string;
  fineDate?: string;
  productName: string;
  escalationLetter?: string;
  evidenceChecklist?: string;
}

function generatePDF(content: string, title: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 65, right: 65 },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header line
    doc
      .moveTo(65, 45)
      .lineTo(530, 45)
      .strokeColor("#0d9488")
      .lineWidth(2)
      .stroke();

    // Title
    doc
      .fontSize(9)
      .fillColor("#64748b")
      .text(title, 65, 52, { align: "right" });

    doc.moveDown(1);

    // Letter content
    const lines = content.split("\n");
    let y = doc.y;

    for (const line of lines) {
      if (y > 750) {
        doc.addPage();
        y = 60;
        doc.y = y;
      }

      const trimmed = line.trim();

      // Detect heading-like lines (all caps or starts with RE:)
      if (
        trimmed.startsWith("RE:") ||
        trimmed.startsWith("Dear ") ||
        trimmed.startsWith("Yours ")
      ) {
        doc.fontSize(11).fillColor("#1e293b").font("Helvetica-Bold");
        doc.text(trimmed, { lineGap: 4 });
        doc.font("Helvetica");
      } else if (trimmed === "") {
        doc.moveDown(0.4);
      } else if (trimmed.match(/^\d+\.\s/)) {
        // Numbered list items
        doc.fontSize(10.5).fillColor("#334155").font("Helvetica");
        doc.text(trimmed, { lineGap: 3, indent: 15 });
      } else if (trimmed.startsWith("- ")) {
        doc.fontSize(10.5).fillColor("#334155").font("Helvetica");
        doc.text(trimmed, { lineGap: 3, indent: 15 });
      } else {
        doc.fontSize(10.5).fillColor("#334155").font("Helvetica");
        doc.text(trimmed, { lineGap: 3 });
      }

      y = doc.y;
    }

    // Footer
    doc.moveDown(2);
    doc
      .moveTo(65, doc.y)
      .lineTo(530, doc.y)
      .strokeColor("#e2e8f0")
      .lineWidth(0.5)
      .stroke();
    doc.moveDown(0.5);
    doc
      .fontSize(8)
      .fillColor("#94a3b8")
      .text(
        "Generated by FineCheck (appealafine.co.uk). This is a document preparation service, not legal advice.",
        { align: "center" }
      );

    doc.end();
  });
}

export async function POST(request: Request) {
  try {
    const body: SendLetterRequest = await request.json();

    if (!body.email || !body.email.includes("@")) {
      return NextResponse.json(
        { error: "Valid email is required" },
        { status: 400 }
      );
    }

    if (!body.letterContent) {
      return NextResponse.json(
        { error: "Letter content is required" },
        { status: 400 }
      );
    }

    const recipient =
      body.operatorName || body.councilName || "the parking operator";
    const fineLabel =
      body.fineType === "private" ? "parking charge" : "Penalty Charge Notice";
    const subject = `Your Appeal Letter: ${recipient}`;
    const dateStr = new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

    // Generate PDF of the main appeal letter
    const attachments: { filename: string; content: Buffer }[] = [];

    const mainPdf = await generatePDF(
      body.letterContent,
      `Appeal Letter: ${recipient}`
    );
    attachments.push({
      filename: `Appeal-Letter-${recipient.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.pdf`,
      content: mainPdf,
    });

    // Generate escalation letter PDF if premium
    if (body.escalationLetter) {
      const escalationPdf = await generatePDF(
        body.escalationLetter,
        `Escalation Letter: ${recipient}`
      );
      attachments.push({
        filename: `Escalation-Letter-${recipient.replace(/\s+/g, "-")}.pdf`,
        content: escalationPdf,
      });
    }

    // Build professional email
    const htmlBody = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">

        <div style="background: #0d9488; padding: 28px 24px; text-align: center; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 22px; font-weight: 700;">Your Appeal Letter is Ready</h1>
          <p style="color: #ccfbf1; margin: 8px 0 0; font-size: 14px;">Your personalised letter is attached as a PDF</p>
        </div>

        <div style="padding: 28px 24px; background: #ffffff; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0;">

          <p style="margin-top: 0; font-size: 15px;">Hi,</p>

          <p style="font-size: 15px; line-height: 1.6;">Your personalised appeal letter for the <strong>${escapeHtml(fineLabel)}</strong> from <strong>${escapeHtml(recipient)}</strong> is attached to this email as a PDF.</p>

          <div style="background: #f0fdfa; border: 2px solid #99f6e4; border-radius: 10px; padding: 18px; margin: 24px 0;">
            <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
              <tr>
                <td style="padding: 4px 0; color: #64748b; width: 120px;">Issued by</td>
                <td style="padding: 4px 0; color: #1e293b; font-weight: 600;">${escapeHtml(recipient)}</td>
              </tr>
              ${body.vehicleReg ? `<tr><td style="padding: 4px 0; color: #64748b;">Vehicle</td><td style="padding: 4px 0; color: #1e293b; font-weight: 600;">${escapeHtml(body.vehicleReg)}</td></tr>` : ""}
              ${body.location ? `<tr><td style="padding: 4px 0; color: #64748b;">Location</td><td style="padding: 4px 0; color: #1e293b;">${escapeHtml(body.location)}</td></tr>` : ""}
              ${body.fineDate ? `<tr><td style="padding: 4px 0; color: #64748b;">Date</td><td style="padding: 4px 0; color: #1e293b;">${escapeHtml(body.fineDate)}</td></tr>` : ""}
              <tr>
                <td style="padding: 4px 0; color: #64748b;">Product</td>
                <td style="padding: 4px 0; color: #1e293b;">${escapeHtml(body.productName)}</td>
              </tr>
              <tr>
                <td style="padding: 4px 0; color: #64748b;">Generated</td>
                <td style="padding: 4px 0; color: #1e293b;">${dateStr}</td>
              </tr>
            </table>
          </div>

          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 18px; margin: 24px 0;">
            <h3 style="margin: 0 0 12px; font-size: 15px; color: #1e293b;">Attached Files</h3>
            <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 8px;">
              <span style="font-size: 20px;">&#128196;</span>
              <span style="font-size: 14px; color: #334155; font-weight: 500;">Appeal Letter (PDF)</span>
            </div>
            ${body.escalationLetter ? `<div style="display: flex; align-items: center; gap: 10px; margin-bottom: 8px;"><span style="font-size: 20px;">&#128196;</span><span style="font-size: 14px; color: #334155; font-weight: 500;">Escalation Letter (PDF)</span></div>` : ""}
            ${body.evidenceChecklist ? `<div style="display: flex; align-items: center; gap: 10px;"><span style="font-size: 20px;">&#9745;</span><span style="font-size: 14px; color: #334155; font-weight: 500;">Evidence Checklist (below)</span></div>` : ""}
          </div>

          ${
            body.evidenceChecklist
              ? `
          <div style="background: #fffbeb; border: 1px solid #fde68a; border-radius: 10px; padding: 18px; margin: 24px 0;">
            <h3 style="margin: 0 0 10px; font-size: 14px; color: #92400e; text-transform: uppercase; letter-spacing: 0.05em;">Evidence Checklist</h3>
            <pre style="white-space: pre-wrap; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 13px; line-height: 1.6; color: #78350f; margin: 0;">${escapeHtml(body.evidenceChecklist)}</pre>
          </div>`
              : ""
          }

          <div style="background: #f0fdfa; border-left: 4px solid #0d9488; padding: 16px 18px; margin: 24px 0; border-radius: 0 8px 8px 0;">
            <h4 style="margin: 0 0 10px; color: #0f766e; font-size: 14px; font-weight: 700;">Before You Send Your Letter</h4>
            <ol style="font-size: 13px; color: #115e59; padding-left: 18px; margin: 0; line-height: 1.8;">
              <li>Open the attached PDF and replace <strong>[YOUR NAME]</strong> and <strong>[YOUR ADDRESS]</strong> with your real details</li>
              <li>Review the letter carefully and adjust any specifics</li>
              <li>Print or email it to ${escapeHtml(recipient)}'s appeals department</li>
              <li>Attach supporting evidence (photos, receipts, bank statements)</li>
              <li>Keep a copy of everything you send</li>
              <li>Submit before your appeal deadline expires</li>
            </ol>
          </div>

          <div style="text-align: center; margin: 28px 0 16px;">
            <a href="https://appealafine.co.uk/guides" style="display: inline-block; background: #0d9488; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-size: 14px; font-weight: 600;">Read Our Appeal Guides</a>
          </div>
        </div>

        <div style="background: #1e293b; padding: 20px 24px; text-align: center; border-radius: 0 0 12px 12px;">
          <p style="color: #e2e8f0; font-size: 13px; margin: 0 0 6px; font-weight: 600;">FineCheck</p>
          <p style="color: #94a3b8; font-size: 11px; margin: 0;">
            <a href="https://appealafine.co.uk" style="color: #5eead4; text-decoration: none;">appealafine.co.uk</a>
          </p>
          <p style="color: #64748b; font-size: 10px; margin: 10px 0 0; line-height: 1.5;">
            FineCheck provides document preparation services. We are not a law firm and do not provide legal advice.
            If you need legal advice, please consult a qualified solicitor.
          </p>
        </div>
      </div>`;

    const resend = getResend();
    const { error } = await resend.emails.send({
      from: "Appeal a Fine <appeals@appealafine.co.uk>",
      to: body.email,
      subject,
      html: htmlBody,
      attachments: attachments.map((a) => ({
        filename: a.filename,
        content: a.content,
      })),
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { error: "Failed to send email" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Send letter error:", error);
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
