import { Product } from '@/lib/types';

export const PRODUCTS: Record<string, Product> = {
  'standard-letter': {
    id: 'standard-letter',
    name: 'Standard Appeal Letter',
    price: 299,
    wasPrice: 599,
    description: 'AI-generated personalised appeal letter using the correct legal grounds for your specific situation.',
    features: [
      'Personalised to your circumstances',
      'Correct legal references',
      'Formatted for submission',
      'Deadline reminder'
    ]
  },
  'premium-pack': {
    id: 'premium-pack',
    name: 'Premium Appeal Pack',
    price: 499,
    wasPrice: 999,
    description: 'Everything in Standard plus escalation template, evidence checklist, and operator-specific strategy guide.',
    features: [
      'Everything in Standard',
      'Escalation letter if rejected',
      'Evidence collection checklist',
      'Operator-specific strategy',
      'Second-stage appeal template'
    ]
  },
  'escalation-pack': {
    id: 'escalation-pack',
    name: 'Escalation Pack',
    price: 1999,
    description: 'For fines past the appeal stage: debt collector response letters, POPLA/IAS rejection next steps, Letter Before Claim reply, and a full court defence preparation pack.',
    features: [
      'Debt recovery response letter (DCBL, DRP, Trace, ZZPS)',
      'POPLA/IAS rejected: next steps letter and guide',
      'Letter Before Claim response + protocol checklist',
      'Court defence checklist + witness statement skeleton',
      'Stage-by-stage escalation decision guide',
    ]
  },
  // Personalised reply for a charge past the first appeal. Generated by the
  // same pipeline as the Standard letter with a stage-specific prompt
  // (src/lib/stage-letter.ts). Recommended by the assessment at the rejected,
  // POPLA/IAS-rejected, debt-collector and Letter Before Claim stages; a court
  // claim is sent to the Escalation Pack instead.
  'stage-reply-letter': {
    id: 'stage-reply-letter',
    name: 'Escalation Reply Letter',
    price: 999,
    description: 'A personalised reply for a parking charge past the first appeal: the POPLA or IAS submission after a rejection, the response to a debt collector, or the Pre-Action Protocol reply to a Letter Before Claim.',
    features: [
      'Written for the exact stage you are at',
      'POPLA or IAS submission after a rejected appeal',
      'Debt collector reply citing POFA 2012 Schedule 4 and the operator code',
      'Letter Before Claim reply in the Pre-Action Protocol format',
      'Requests every document you are entitled to, ready to send',
    ]
  },
};

export const DISCOUNT_CODES: Record<string, { percentOff: number; maxUses?: number }> = {
  LAUNCH50: { percentOff: 50, maxUses: 100 },
  TESTFREE: { percentOff: 100 }
};
